##服务端口
#server:
#  port: 8002
#
##服务名
#spring:
#  application:
#    name: cloud-provider-payment
##数据源
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://192.168.239.128:3307/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
##nacos注册中心
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.239.128:8848
#
##mybatis
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.yq.cloud.provider.payment.domain
#
##健康检测
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

spring:
  profiles:
    active: dev